config/routes.rb
Rails.application.routes.draw do
  get 'series/show'
  root 'top#index'
  resources :posts, only: %i[index show]
  resources :categories, only: %i[show]
  resources :series
  resources :tags, only: %i[index show]
  resources :about, only: %i[index]

  namespace :admin do
    root 'home#index'
    resources :posts, only: %i[new show create edit update destroy] do
      get :all, :published, :drafts, on: :collection
    end
    resources :categories, only: %i[index show create edit update destroy]
    resources :images, only: %i[index create]
    resources :writers, only: %i[index edit update]
    post 'writers/:id/prof_img' => 'writers#prof_img'
    resources :series, only: %i[index show create edit update destroy]
  end



  get 'top/contact' => 'top#contact'
  get 'top/link' => 'top#link'
  get '/sign_in_6851' => 'top#sign_in'
  post '/login' => 'top#login'
  post '/logout' => 'top#logout'

  get '*path', to: 'application#render_404' if Rails.env.production?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  validates :name, presence: true

  def to_param
    name
  end
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file_name, ImageUploader
end

app/models/popular_post.rb
class PopularPost < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :writer
  belongs_to :series

  has_one :popular_post, dependent: :destroy

  before_create :time_create
  before_update :time_update

  acts_as_taggable

  validates :title, presence: true
  validates :category_id, presence: true
  validates :text, presence: true
  validates :image, presence: true

  mount_uploader :image, PostImageUploader

  enum published: { Draft: false, Published: true }

  scope :default_order, -> { order('time desc') }
  scope :published, -> { where(published: true) }
  scope :drafts, -> { where(published: false) }
  scope :favorite, -> { where(favorite: true) }

  def to_param
    slug
  end

  def previous
    Post.published.default_order.find_by('created_at < ?', created_at)
  end

  def next
    Post.published.default_order.where('created_at > ?', created_at).reverse.first
  end

  private

  def time_create
    if self.Published?
      self.time = Time.zone.now
    end
  end

  def time_update
    if self.published_changed?(from: "Draft", to:"Published")
      self.time = Time.zone.now
    elsif self.published_changed?(from: "Published", to:"Draft")
      self.time = nil
    end
  end

end

app/models/series.rb
class Series < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/models/tags.rb
module ActsAsTaggableOn
  class Tag < ::ActiveRecord::Base
    def to_param
      name
    end
  end
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published.includes(:category).default_order.page(params[:page]).per(8)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end

  def show
    @post = Post.published.find_by(slug: params[:id])
    #@popular_posts = PopularPost.includes(post: :category).map(&:post).take(5)
    if @post.series
      @similar_posts = @post.series.posts.published.where('id != ?', @post.id).default_order.limit(4)
    else
      @similar_posts = @post.category.posts.published.where('id != ?', @post.id).default_order.limit(4)
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Post.tags_on(:tags)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
  def show
    @tag = ActsAsTaggableOn::Tag.find_by(name: params[:id])
    @posts = Post.tagged_with(@tag.name).published.default_order.page(params[:page]).per(12)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @posts = Post.published.includes(:category).default_order.page(params[:page]).per(8)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
  def aboutus
  end
  def contact
  end
  def link
  end

  def sign_in
  end

  def login
    @writer = Writer.find_by(code: params[:code], pass: params[:pass])
    if @writer
      session[:writer_id] = @writer.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      @error_message = "ユーザー名またはパスワードが間違っています．"
      @writer_code = params[:code]
      @pass = params[:pass]
      render("top/sign_in")
    end
  end

  def logout
    session[:writer_id] = nil
    flash[:notice] = "ログアウトしました．"
    redirect_to("/")
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
    }
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/shared/_aboutus.html.erb
<div class="sub-wrapper">
  <div class="container-fluid sub-container">
    <div class="row sub">
      <div class="col-md-12 col-xs-12 profile">
        <h2 class="profile-title">スバ賢編集部</h2>
          <div class="profile-info--official">
            <%= link_to "https://twitter.com/subakashi_media", {class: "profile-info--sns icon-sns icon-twitter", target: "_blank"} do %>
              <%= icon("fab", "twitter fa-2x") %>
              <% end %>
              <%= link_to "https://www.youtube.com/channel/UC1nhXEpwEf51J31vDBg6g-Q?view_as=subscriber", {class: "profile-info--sns icon-sns icon-youtube", target: "_blank"} do %>
              <%= icon("fab", "youtube fa-2x") %>
              <% end %>
            </div>



        <% @writers.each do |writer| %>
        <div class="col-md-12 col-sm-12 col-xs-12 profile-wrapper">
          <div class="col-md-5 col-sm-5 col-xs-5 profile-image">
            <%= image_tag "/assets/prof_#{writer.id}.jpg", class: "profile-image--item" %>
          </div>
          <div class="col-md-7 col-sm-7 col-xs-7 profile-info">
            <p class="profile-info--name"><%= writer.name %></p>
            <div class="profile-info--link">
              <% if writer.twitter? %>
              <%= link_to "#{writer.twitter}", {class: "profile-info--sns icon-sns icon-twitter", target: "_blank"} do %>
                <%= icon("fab", "twitter fa-lg") %>
              <% end %>
              <% end %>
              <% if writer.instagram? %>
              <%= link_to "#{writer.instagram}", {class: "profile-info--sns icon-sns icon-instagram", target: "_blank"} do %>
              <%= icon("fab", "instagram fa-lg") %>
              <% end %>
              <% end %>
              <% if writer.youtube? %>
              <%= link_to "#{writer.youtube}", {class: "profile-info--sns icon-sns icon-youtube", target: "_blank"} do %>
                <%= icon("fab", "youtube fa-lg") %>
              <% end %>
              <% end %>
            </div>
            <div class="profile-info--description">
              <p><%= writer.about %></p>
            </div>
          </div>
        </div>
        <% end %>
        <div class="profile-info--detail">
          <%= link_to "もっと詳しく", about_index_path, class: "btn btn-outline-default btn-round" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_admin_side.html.erb
<div class="admin-side">
  <div class="admin-side--header">
    <%= link_to 'スバ賢メディア', root_path, target: "_blank" %>
  </div>
  <div class="admin-side--menu">
    <ul>
      <li class="admin-side--menu_item">
        <%= icon("fas", "home") %><%= link_to "ダッシュボード", admin_root_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= icon("fas", "users") %><%= link_to "ライター", admin_writers_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= icon("fas", "edit") %><%= link_to "記事を書く", new_admin_post_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= icon("far", "file-code") %><%= link_to "記事の管理", all_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item__sub">
        <%= link_to "- 公開記事", published_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item__sub">
        <%= link_to "- 非公開記事", drafts_admin_posts_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= icon("fas", "tags") %><%= link_to "カテゴリー", admin_categories_path %>
      </li>
      <li class="admin-side--menu_item">
        <%= icon("fas", "link") %><%= link_to "連載シリーズ", admin_series_index_path %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-menu">

  </div>
  <div class="footer-copyright">
    <p>©Copyright 2020 スバ賢編集部 All Rights Reserved.</p>
  </div>

</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-default navbar-all">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="top-title">
        <%= link_to image_tag("header-logo.png"), root_path, class: "top-title-link" %>
      </div>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right navbar-links">
        <li>
          <%= link_to 'スバ賢とは', about_index_path, class: "navbar-link" %>
        </li>
        <li>
          <%= link_to '関連リンク', top_link_path, class: "navbar-link" %>
        </li>
        <li>
          <%= link_to 'お問い合わせ', top_contact_path, class: "navbar-link" %>
        </li>
        <% if @current_writer %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle navbar-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ログイン中 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to '記事管理', admin_root_path %></li>
              <li><%= link_to 'ログアウト', '/logout', method: :post %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_post.html.erb
<div class="col-md-6 post-list" ontouchstart="">
  <%= link_to post, class: "post-item" do %>
    <div class="post-item--side">
      <div class="post-item--image">
        <%= image_tag post.image.url(:thumb), class: "post-item--image__item" %>
      </div>
    </div>
    <div class="post-item--main">
      <p class="post-item--main_title"><%= post.title %></p>
      <p class="post-item--main_info">
        <span class="post-item--main_info__category">
          <%= post.category.name %>
        </span>
        <span class="post-item--main_info__date">
          <%= post.time.strftime("%Y/%m/%d") %>
        </span>
      </p>
    </div>
  <% end %>
</div>

app/views/shared/_post_list.html.erb
<header>
  <%= render 'shared/navbar' %>
  <div class="container-fluid slider-container">
    <div class="post-slider">
      <% @slider_posts.each do |slide_post| %>
        <div class="post-slider--item">
          <%= link_to slide_post do %>
            <%= image_tag slide_post.image.url(:thumb), class:"post-slider--item_image" %>
            <div class="post-slider--item_title">
              <%= slide_post.title %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</header>
<div class="main-wrapper">
  <div class="container-fluid main-container">
    <div class="posts-wrapper">
      <div class="posts">
        <h2 class="main-title"><%= main_title %></h2>
        <p class="main-description"><%= description %></p>
        <div class="posts-wrapper">
          <%= render partial: 'shared/post', collection: @posts %>
        </div>
        <div class="posts-pagination">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/aboutus' %>
<%= render 'shared/footer' %>

app/views/shared/_preview_top.html.erb
<header>
  <nav class="navbar-default navbar-all">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="top-title">
          <%= link_to image_tag("header-logo.png"), root_path, class: "top-title-link" %>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right navbar-links">
          <li>
            <%= link_to 'スバ賢とは', about_index_path, class: "navbar-link" %>
          </li>
          <li>
            <%= link_to '関連リンク', top_link_path, class: "navbar-link" %>
          </li>
          <li>
            <%= link_to 'お問い合わせ', top_contact_path, class: "navbar-link" %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  <div class="container-fluid slider-container">
    <div class="menu-slider">
      <div class="menu-slider--item">

      </div>

      <div class="menu-slider--item">

      </div>

    </div>

  </div>
</header>

<div class="main-wrapper">
  <div class="main-container">
    <div class="posts">
      <h1 class="main-title">New Posts</h1>
      <div class="posts-wrapper">
        <%= render partial: 'shared/post', collection: @posts %>
      </div>
      <div class="posts-pagination">
        <%= paginate @posts %>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/aboutus' %>
<%= render 'shared/footer' %>