config/routes.rb
Rails.application.routes.draw do
  get 'series/show'
  root 'top#index'
  resources :posts, only: %i[index show]
  resources :categories, only: %i[show]
  resources :series
  resources :tags, only: %i[index show]
  resources :about, only: %i[index]

  namespace :admin do
    root 'home#index'
    resources :posts, only: %i[new show create edit update destroy] do
      get :all, :published, :drafts, on: :collection
    end
    resources :categories, only: %i[index show create edit update destroy]
    resources :images, only: %i[index create]
    resources :writers, only: %i[index edit update]
    post 'writers/:id/prof_img' => 'writers#prof_img'
    resources :series, only: %i[index show create edit update destroy]
  end



  get 'top/contact' => 'top#contact'
  get 'top/link' => 'top#link'
  get '/sign_in_6851' => 'top#sign_in'
  post '/login' => 'top#login'
  post '/logout' => 'top#logout'

  get '*path', to: 'application#render_404' if Rails.env.production?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  validates :name, presence: true

  def to_param
    name
  end
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file_name, ImageUploader
end

app/models/popular_post.rb
class PopularPost < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :writer
  belongs_to :series

  has_one :popular_post, dependent: :destroy

  before_create :time_create
  before_update :time_update

  acts_as_taggable

  validates :title, presence: true
  validates :category_id, presence: true
  validates :text, presence: true
  validates :image, presence: true

  mount_uploader :image, PostImageUploader

  enum published: { Draft: false, Published: true }

  scope :default_order, -> { order('time desc') }
  scope :published, -> { where(published: true) }
  scope :drafts, -> { where(published: false) }
  scope :favorite, -> { where(favorite: true) }

  def to_param
    slug
  end

  def previous
    Post.published.default_order.find_by('created_at < ?', created_at)
  end

  def next
    Post.published.default_order.where('created_at > ?', created_at).reverse.first
  end

  private

  def time_create
    if self.Published?
      self.time = Time.zone.now
    end
  end

  def time_update
    if self.published_changed?(from: "Draft", to:"Published")
      self.time = Time.zone.now
    elsif self.published_changed?(from: "Published", to:"Draft")
      self.time = nil
    end
  end

end

app/models/series.rb
class Series < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/models/tags.rb
module ActsAsTaggableOn
  class Tag < ::ActiveRecord::Base
    def to_param
      name
    end
  end
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_categories

  def index
    @category = Category.new
  end

  def show
    @category = Category.find_by(name: params[:id])
    @posts = @category.posts.includes(:category).default_order.page(params[:page]).per(8)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: 'カテゴリを作成しました。'
    else
      flash.alert = 'カテゴリーの作成に失敗しました。'
      render :index
    end
  end

  def destroy
    @category = Category.find_by(id: params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  def edit
    @category = Category.find_by(id: params[:id])
  end

  def update
    @category = Category.find_by(id: params[:id])
    @category.name = params[:name]
    @category.save
    redirect_to admin_categories_path
  end
  private



  def category_params
    params.require(:category).permit(:name)
  end

  def set_categories
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(name: params[:id])
    @posts = @category.posts.published.default_order.page(params[:page]).per(12) if @category.posts
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published.includes(:category).default_order.page(params[:page]).per(8)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end

  def show
    @post = Post.published.find_by(slug: params[:id])
    #@popular_posts = PopularPost.includes(post: :category).map(&:post).take(5)
    if @post.series
      @similar_posts = @post.series.posts.published.where('id != ?', @post.id).default_order.limit(4)
    else
      @similar_posts = @post.category.posts.published.where('id != ?', @post.id).default_order.limit(4)
    end
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def show
      @series = Series.find_by(id: params[:id])
      @posts = @series.posts.published.default_order.page(params[:page]).per(12) if @series.posts
      @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Post.tags_on(:tags)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
  def show
    @tag = ActsAsTaggableOn::Tag.find_by(name: params[:id])
    @posts = Post.tagged_with(@tag.name).published.default_order.page(params[:page]).per(12)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @posts = Post.published.includes(:category).default_order.page(params[:page]).per(8)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
  def aboutus
  end
  def contact
  end
  def link
  end

  def sign_in
  end

  def login
    @writer = Writer.find_by(code: params[:code], pass: params[:pass])
    if @writer
      session[:writer_id] = @writer.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      @error_message = "ユーザー名またはパスワードが間違っています．"
      @writer_code = params[:code]
      @pass = params[:pass]
      render("top/sign_in")
    end
  end

  def logout
    session[:writer_id] = nil
    flash[:notice] = "ログアウトしました．"
    redirect_to("/")
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
    }
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/categories/edit.html.erb
<% set_meta_tags noindex: true %>
<script>
  $(function() {
    $("html").addClass("admin-wrap");
    $("body").addClass("admin-wrap");
    $(".wrap").addClass("admin-wrap");
  })
</script>
<div class="admin">
  <%= render 'shared/admin_side' %>
  <div class="admin-main">
    <div class="admin-main--header">
      <h2>カテゴリーの編集</h2>
    </div>
    <div class="admin-main--body">
      <div class="writer">
        <%= form_tag(admin_category_path(@category.id), method: :patch ) do %>
        <div class="form">
          <div class="form-body">
            <p>
              カテゴリー名
            </p>
            <input name="name" value="<%= @category.name %>">
            <input type="submit" value="保存">
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% set_meta_tags noindex: true %>
<script>
  $(function() {
    $("html").addClass("admin-wrap");
    $("body").addClass("admin-wrap");
    $(".wrap").addClass("admin-wrap");
  })
</script>
<div class="admin">
  <%= render 'shared/admin_side' %>
  <div class="admin-main">
    <div class="admin-main--header">
      <h2>カテゴリー</h2>
    </div>
    <div class="admin-main--body">
      <div class="row categories">
        <% @categories.each do |category|%>
          <%= link_to "#{category.name}", admin_category_path(category) %>
          <%= link_to edit_admin_category_path(category.id) do %><%= icon('fas','edit')  %><% end %>
          <%= link_to admin_category_path(category.id), method: :delete, data: {confirm: "削除されたカテゴリーは復元できません．削除しますか？"} do %><%= icon('fas','times')  %><% end %>
        <% end %>
      </div>
      <div class="row categories">
        <div class="col-md-6 category-new">
          <div class="form-group">
            <%= form_for [:admin, @category] do |f| %>
              <div class="col-sm-10 category-new--form">
                <%= f.text_field :name, class:"col-sm-10 form-control input-lg" %>
              </div>
              <%= button_tag type: 'submit', class:"btn btn-primary col-sm-2" do %>
                <%= icon("far", "plus-square") %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% set_meta_tags noindex: true %>
<%= render "admin/posts/post_list", title: @category.name %>

app/views/categories/show.html.erb
<% set_meta_tags title: @category.name, og: { title: @category.name, type: 'website' }, twitter: { title: @category.name } %>
<%= render 'shared/post_list', main_title: @category.name, description: "カテゴリー #{@category.name} の記事一覧です．" %>