config/routes.rb
Rails.application.routes.draw do
  get 'series/show'
  root 'top#index'
  resources :posts, only: %i[index show]
  resources :categories, only: %i[show]
  resources :series
  resources :tags, only: %i[index show]
  resources :about, only: %i[index]

  namespace :admin do
    root 'home#index'
    resources :posts, only: %i[new show create edit update destroy] do
      get :all, :published, :drafts, on: :collection
    end
    resources :categories, only: %i[index show create edit update destroy]
    resources :images, only: %i[index create]
    resources :writers, only: %i[index edit update]
    post 'writers/:id/prof_img' => 'writers#prof_img'
    resources :series, only: %i[index show create edit update destroy]
  end



  get 'top/contact' => 'top#contact'
  get 'top/link' => 'top#link'
  get '/sign_in_6851' => 'top#sign_in'
  post '/login' => 'top#login'
  post '/logout' => 'top#logout'

  get '*path', to: 'application#render_404' if Rails.env.production?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify

  validates :name, presence: true

  def to_param
    name
  end
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file_name, ImageUploader
end

app/models/popular_post.rb
class PopularPost < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :writer
  belongs_to :series

  has_one :popular_post, dependent: :destroy

  before_create :time_create
  before_update :time_update

  acts_as_taggable

  validates :title, presence: true
  validates :category_id, presence: true
  validates :text, presence: true
  validates :image, presence: true

  mount_uploader :image, PostImageUploader

  enum published: { Draft: false, Published: true }

  scope :default_order, -> { order('time desc') }
  scope :published, -> { where(published: true) }
  scope :drafts, -> { where(published: false) }
  scope :favorite, -> { where(favorite: true) }

  def to_param
    slug
  end

  def previous
    Post.published.default_order.find_by('created_at < ?', created_at)
  end

  def next
    Post.published.default_order.where('created_at > ?', created_at).reverse.first
  end

  private

  def time_create
    if self.Published?
      self.time = Time.zone.now
    end
  end

  def time_update
    if self.published_changed?(from: "Draft", to:"Published")
      self.time = Time.zone.now
    elsif self.published_changed?(from: "Published", to:"Draft")
      self.time = nil
    end
  end

end

app/models/series.rb
class Series < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/models/tags.rb
module ActsAsTaggableOn
  class Tag < ::ActiveRecord::Base
    def to_param
      name
    end
  end
end

app/models/writer.rb
class Writer < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to edit_admin_post_path(@post), notice: '記事を投稿しました。'
    else
      flash.alert = '投稿に失敗しました。'
      render :new
    end
  end

  def show
    @post = Post.find_by(slug: params[:id])
  end

  def edit
    @post = Post.find_by(slug: params[:id])
  end

  def update
    @post = Post.find_by(slug: params[:id])
    # binding.pry
    if @post.update(post_params)
      redirect_to edit_admin_post_path(@post), notice: '記事を更新しました。'
    else
      flash.alert = '記事の更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    post = Post.find_by(slug: params[:id])
    if post.destroy
      flash[:notice] = '削除しました。'
      redirect_back(fallback_location: all_admin_posts_path)
    else
      flash.alert = '削除できませんでした。'
      redirect_back(fallback_location: all_admin_posts_path)
    end
  end

  def all
    @posts = Post.default_order.page(params[:page]).per(10)
  end

  def published
    @posts = Post.published.default_order.page(params[:page]).per(10)
  end

  def drafts
    @posts = Post.drafts.default_order.page(params[:page]).per(10)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :image, :published, :category_id, :tag_list, :series_id, :writer_id, :slug, :favorite, :description, :comment)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find_by(name: params[:id])
    @posts = @category.posts.published.default_order.page(params[:page]).per(12) if @category.posts
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published.includes(:category).default_order.page(params[:page]).per(8)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end

  def show
    @post = Post.published.find_by(slug: params[:id])
    #@popular_posts = PopularPost.includes(post: :category).map(&:post).take(5)
    if @post.series
      @similar_posts = @post.series.posts.published.where('id != ?', @post.id).default_order.limit(4)
    else
      @similar_posts = @post.category.posts.published.where('id != ?', @post.id).default_order.limit(4)
    end
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def show
      @series = Series.find_by(id: params[:id])
      @posts = @series.posts.published.default_order.page(params[:page]).per(12) if @series.posts
      @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Post.tags_on(:tags)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
  def show
    @tag = ActsAsTaggableOn::Tag.find_by(name: params[:id])
    @posts = Post.tagged_with(@tag.name).published.default_order.page(params[:page]).per(12)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @posts = Post.published.includes(:category).default_order.page(params[:page]).per(8)
    @slider_posts = Post.published.favorite.default_order.limit(8)
  end
  def aboutus
  end
  def contact
  end
  def link
  end

  def sign_in
  end

  def login
    @writer = Writer.find_by(code: params[:code], pass: params[:pass])
    if @writer
      session[:writer_id] = @writer.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      @error_message = "ユーザー名またはパスワードが間違っています．"
      @writer_code = params[:code]
      @pass = params[:pass]
      render("top/sign_in")
    end
  end

  def logout
    session[:writer_id] = nil
    flash[:notice] = "ログアウトしました．"
    redirect_to("/")
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
  def status(post)
    if post.Published?
      button_tag(post.published, class: 'btn btn-primary')
    elsif post.Draft?
      button_tag(post.published, class: 'btn btn-secondary')
    end
  end

  def md_to_html(text)
    options = {
      filter_html: false,
      hard_wrap: true,
      space_after_headers: true
    }

    extensions = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      space_after_headers: true,
      highlight: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def previous_post(post)
    if post
      link_to(post.title, post, class: 'previous_post')
    else
      link_to(icon('fas','home lg') + ' トップ', root_path, class: 'next_post')
    end
  end

  def next_post(post)
    if post
      link_to(post.title, post, class: 'next_post')
    else
      link_to(icon('fas','home lg') + ' トップ', root_path, class: 'next_post')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
    }
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/posts/_popular_post.html.erb
<div class="side-bar--post" ontouchstart="">
  <div class="side-bar--post_index hidden-xs"><%= popular_post_counter + 1 %></div>
  <%= link_to popular_post, class: "side-bar--post-item" do %>
    <div class="side-bar--post-item--side">
      <%= image_tag popular_post.image.url(:thumb_mini), class: "side-bar--post-item--side_image" %>
    </div>
    <div class="side-bar--post-item--main">
      <p class="side-bar--post-item--main_title">
        <%= popular_post.title %>
      </p>
      <p class="side-bar--post-item--main_info">
        <span class="side-bar--post-item--main_info__category">
          <%= popular_post.category.name %>
        </span>
        <span class="side-bar--post-item--main_info__date">
          <%= popular_post.created_at.to_s(:published_on) %>
        </span>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/_similar_post.html.erb
<div class="col-md-3 col-sm-6 col-xs-6 similar-post" ontouchstart="">
  <div class="row">
    <%= link_to similar_post do %>
      <div class="col-md-12 col-sm-12">
        <%= image_tag similar_post.image.url(:thumb_mini), class:"similar-post--image" %>
      </div>
      <div class="similar-post--title col-md-12 col-sm-12 ">
        <%= similar_post.title %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% set_meta_tags title: "All Posts", og: { title: "All Posts", type: 'website' }, twitter: { title: "All Posts" } %>
<%= render 'shared/post_list', main_title: "All Posts" %>

app/views/posts/show.html.erb
<% set_meta_tags title: @post.title, description: @post.description, keywords: @post.tag_list.join(","), og: { title: @post.title, description: @post.description, type: 'article', image: @post.image.url }, twitter: { title: @post.title, description: @post.description, image: @post.image.url } %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/monokai.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<header>
  <%= render 'shared/navbar' %>
</header>

<div class="post-wrapper">
  <div class="container-fluid main-container">
    <div class="row">
      <div class="col-md-9 col-lg-8 col-lg-offset-1">
        <div class="post">
          <h1 class="post-title"><%= @post.title %></h1>
          <div class="post-thumbnail">
            <%= image_tag @post.image.url(:thumb), class: "post-thumbnail"%>
          </div>
          <div class="post-date">
            <div class="post-date-published">
              記事公開日：<%=  @post.time.strftime('%Y/%m/%d') %>
            </div>
            <div class="post-date-published">
              最終更新日：<%=  @post.updated_at.strftime('%Y/%m/%d') %>
            </div>
          </div>
          <div class="post-info" ontouchstart="">
            <div class="post-info--category">
              <%= icon("fas", "home") %> <%= link_to "スバ賢メディア", root_path %> / <%= link_to @post.category.name, @post.category %> / <% if @post.series.name!="読切" %> <%= link_to @post.series.name, series_path(@post.series.id) %> <% end %>
            </div>
            <div class="post-info--tags">
              <% @post.tags.each do |tag| %>
                <div class="tag"><%= link_to "##{tag.name}", "../tags/#{tag.name}" %></div>
              <% end %>
            </div>
          </div>
          <div class="post-text">
            <%= md_to_html(@post.text) %>
          </div>
          <div class="writer-info">
            <p class="this-article">この記事を書いたのは…</p>
            <div class="writer-info--comment">
              <%= @post.comment %>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 profile-image">
              <%= image_tag "/assets/prof_#{@post.writer.id}.jpg", class: "profile-image--item" %>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 profile-info">
              <p class="profile-info--name"><%= @post.writer.name %></p>
              <div class="profile-info--link">
                <% if @post.writer.twitter? %>
                <%= link_to "#{@post.writer.twitter}", {class: "profile-info--sns icon-sns icon-twitter", target: "_blank"} do %>
                  <%= icon("fab", "twitter fa-lg") %>
                <% end %>
                <% end %>
                <% if @post.writer.instagram? %>
                <%= link_to "#{@post.writer.instagram}", {class: "profile-info--sns icon-sns icon-instagram", target: "_blank"} do %>
                <%= icon("fab", "instagram fa-lg") %>
                <% end %>
                <% end %>
                <% if @post.writer.youtube? %>
                <%= link_to "#{@post.writer.youtube}", {class: "profile-info--sns icon-sns icon-youtube", target: "_blank"} do %>
                  <%= icon("fab", "youtube fa-lg") %>
                <% end %>
                <% end %>
              </div>
              <div class="profile-info--description">
                <p><%= @post.writer.description %></p>
              </div>
              <div class="profile-info--detail">
                <%= link_to "もっと詳しく", about_index_path, class: "btn btn-outline-default btn-round" %>
              </div>
            </div>
          </div>
          <div class="post-sns">
            <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            <a data-pocket-label="pocket" data-pocket-count="horizontal" class="pocket-btn" data-lang="en"></a>
            <script type="text/javascript">!function(d,i){if(!d.getElementById(i)){var j=d.createElement("script");j.id=i;j.src="https://widgets.getpocket.com/v1/j/btn.js?v=1";var w=d.getElementById(i);d.body.appendChild(j);}}(document,"pocket-btn-js");</script>
          </div>
        </div>
        <div class="previous_next">
          <div class="next">
            <span>&lsaquo; <%= next_post(@post.next) %>
            </span>
          </div>
          <div class="previous">
            <span><%= previous_post(@post.previous) %> &rsaquo;</span>
          </div>
        </div>
        <div class="row similar-posts">
          <h4 class="similar-posts--title">関連記事</h4>
          <%= render partial: 'similar_post', collection: @similar_posts, as: :similar_post %>
        </div>
      </div>
      <div class="col-md-3 col-lg-3 sticky bottom-xs">
        <div class="side-bar">
          <div class="side-bar--posts">
            <h2 class="side-title">人気記事</h2>
            <%= render partial: 'popular_post', collection: @popular_posts, as: :popular_post%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/aboutus' %>
<%= render 'shared/footer' %>